### ISSUE TITLE
adding return stdout (if number) and exit status

### ISSUE THREAD

**Issue by yosefy** [adhocteam/script_exporter#1]
hi is it possible to do?
it would save lots of time for us
thanks

**Comment by jkassemi** [comment]
Reporting on stdout may be beyond scope. Would specifying an option to check for content within the stdout or for an expected return code help satisfy the requirements?

**Comment by yosefy** [comment]
why so?
most of the scripts we run we get something , like last example i was asked
to monitor:
need a result of:
############
mysql -e "show full processlist" | grep -c -v Sleep
############
so if i could get the result of your exporter i am done there

other wise:
i run it from script_exporter and push to pushgateway from another script
or put in node_exporter file...
and then get consistent with everything with labels

i would be very happy with first option.

why d u you think its beyond scope?

thanks

**Comment by jkassemi** [comment]
I can see the desired utility of the feature - my concern would be over defining the coercion of the result and ensuring it's only attempted on success. An additional gauge would be required for each configured script to avoid mixing types, as it doesn't make sense to combine successful result counts and mysql process counts, for instance. 

This does go beyond my initial scope - if you're interested in adding the functionality I'd definitely take a look at a PR, but merge would really depend on tight the configuration for this would feel.

**Comment by yosefy** [comment]
amm not really
i usually need the number form stdout
nevermind then

thanks
