### ISSUE TITLE
problem compiling 

### ISSUE THREAD

**Issue by yosefy** [adhocteam/script_exporter#2]
script_exporter.go:4:2: cannot find package "context" in any of:
	/root/go/src/github.com/adhocteam/script_exporter/vendor/context (vendor tree)
	/usr/lib/go/src/context (from $GOROOT)
	/root/go/src/context (from $GOPATH)
script_exporter.go:7:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/root/go/src/github.com/adhocteam/script_exporter/vendor/gopkg.in/yaml.v2 (vendor tree)
	/usr/lib/go/src/gopkg.in/yaml.v2 (from $GOROOT)
	/root/go/src/gopkg.in/yaml.v2 (from $GOPATH)
!! command failed: build -o /root/go/src/github.com/adhocteam/script_exporter/script_exporter -ldflags -linkmode external -extldflags -static -X github.com/adhocteam/script_exporter/vendor/github.com/prometheus/common/version.Version=0.0.1 -X github.com/adhocteam/script_exporter/vendor/github.com/prometheus/common/version.Revision=f03116a5cac1904d4fb4e8a730572c45b3967ea6 -X github.com/adhocteam/script_exporter/vendor/github.com/prometheus/common/version.Branch=master -X github.com/adhocteam/script_exporter/vendor/github.com/prometheus/common/version.BuildUser=root@pa-prometheus1 -X github.com/adhocteam/script_exporter/vendor/github.com/prometheus/common/version.BuildDate=20161121-11:03:56  -extldflags '-static' -a -tags 'netgo static_build' github.com/adhocteam/script_exporter: exit status 1
make: *** [build] Error 1

**Comment by jkassemi** [comment]
I've updated the README to reflect a minimum supported go version of 1.7.3.
